//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/template/AbstractRoutingTemplate.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/routing/template/AbstractRoutingTemplate.h"
#include "com/graphhopper/storage/index/QueryResult.h"
#include "com/graphhopper/util/PointList.h"
#include "com/graphhopper/util/shapes/GHPoint3D.h"
#include "java/util/List.h"

@implementation ComGraphhopperRoutingTemplateAbstractRoutingTemplate

- (PointList *)getWaypoints {
  PointList *pointList = [[[PointList alloc] initWithInt:[((id<JavaUtilList>) nil_chk(queryResults_)) size] withBoolean:YES] autorelease];
  for (QueryResult * __strong qr in queryResults_) {
    [pointList addWithGHPoint:[((QueryResult *) nil_chk(qr)) getSnappedPoint]];
  }
  return pointList;
}

- (instancetype)init {
  return [super init];
}

- (void)dealloc {
  RELEASE_(queryResults_);
  [super dealloc];
}

- (void)copyAllFieldsTo:(ComGraphhopperRoutingTemplateAbstractRoutingTemplate *)other {
  [super copyAllFieldsTo:other];
  ComGraphhopperRoutingTemplateAbstractRoutingTemplate_set_queryResults_(other, queryResults_);
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getWaypoints", NULL, "Lcom.graphhopper.util.PointList;", 0x4, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static const J2ObjcFieldInfo fields[] = {
    { "queryResults_", NULL, 0x4, "Ljava.util.List;", NULL,  },
  };
  static const J2ObjcClassInfo _ComGraphhopperRoutingTemplateAbstractRoutingTemplate = { 1, "AbstractRoutingTemplate", "com.graphhopper.routing.template", NULL, 0x1, 2, methods, 1, fields, 0, NULL};
  return &_ComGraphhopperRoutingTemplateAbstractRoutingTemplate;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGraphhopperRoutingTemplateAbstractRoutingTemplate)
