//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/reader/osm/conditional/ParsedCalendar.java
//

#ifndef _ComGraphhopperReaderOsmConditionalParsedCalendar_H_
#define _ComGraphhopperReaderOsmConditionalParsedCalendar_H_

@class ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum;
@class JavaUtilCalendar;

#include "J2ObjC_header.h"
#include "java/lang/Enum.h"

/**
 @brief This class represents a parsed Date and the parse type.
 <p>
 @author Robin Boldt
 */
@interface ComGraphhopperReaderOsmConditionalParsedCalendar : NSObject {
 @public
  ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum *parseType_;
  JavaUtilCalendar *parsedCalendar_;
}

- (instancetype)initWithComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum:(ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum *)parseType
                                                                  withJavaUtilCalendar:(JavaUtilCalendar *)parsedCalendar;

- (jboolean)isYearless;

- (jboolean)isDayless;

- (jboolean)isDayOnly;

- (JavaUtilCalendar *)getMax;

- (JavaUtilCalendar *)getMin;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGraphhopperReaderOsmConditionalParsedCalendar)

J2OBJC_FIELD_SETTER(ComGraphhopperReaderOsmConditionalParsedCalendar, parseType_, ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum *)
J2OBJC_FIELD_SETTER(ComGraphhopperReaderOsmConditionalParsedCalendar, parsedCalendar_, JavaUtilCalendar *)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(ComGraphhopperReaderOsmConditionalParsedCalendar)

typedef NS_ENUM(NSUInteger, ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType) {
  ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_YEAR_MONTH_DAY = 0,
  ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_YEAR_MONTH = 1,
  ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_MONTH_DAY = 2,
  ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_MONTH = 3,
  ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_DAY = 4,
};

@interface ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum : JavaLangEnum < NSCopying > {
}

- (instancetype)initWithNSString:(NSString *)__name
                         withInt:(jint)__ordinal;

+ (IOSObjectArray *)values;
FOUNDATION_EXPORT IOSObjectArray *ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_values();

+ (ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum *)valueOfWithNSString:(NSString *)name;

FOUNDATION_EXPORT ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum *ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_valueOfWithNSString_(NSString *name);
- (id)copyWithZone:(NSZone *)zone;

@end

FOUNDATION_EXPORT BOOL ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_initialized;
J2OBJC_STATIC_INIT(ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum)

FOUNDATION_EXPORT ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum *ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_values_[];

#define ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_YEAR_MONTH_DAY ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_values_[ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_YEAR_MONTH_DAY]
J2OBJC_ENUM_CONSTANT_GETTER(ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum, YEAR_MONTH_DAY)

#define ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_YEAR_MONTH ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_values_[ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_YEAR_MONTH]
J2OBJC_ENUM_CONSTANT_GETTER(ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum, YEAR_MONTH)

#define ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_MONTH_DAY ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_values_[ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_MONTH_DAY]
J2OBJC_ENUM_CONSTANT_GETTER(ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum, MONTH_DAY)

#define ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_MONTH ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_values_[ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_MONTH]
J2OBJC_ENUM_CONSTANT_GETTER(ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum, MONTH)

#define ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_DAY ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum_values_[ComGraphhopperReaderOsmConditionalParsedCalendar_ParseType_DAY]
J2OBJC_ENUM_CONSTANT_GETTER(ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum, DAY)

J2OBJC_TYPE_LITERAL_HEADER(ComGraphhopperReaderOsmConditionalParsedCalendar_ParseTypeEnum)

#endif // _ComGraphhopperReaderOsmConditionalParsedCalendar_H_
