//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/ch/Path4CH.java
//

#ifndef _Path4CH_H_
#define _Path4CH_H_

@protocol CHEdgeIteratorState;
@protocol ComGraphhopperRoutingWeightingWeighting;
@protocol Graph;

#include "J2ObjC_header.h"
#include "com/graphhopper/routing/PathBidirRef.h"

/**
 @brief Recursivly unpack shortcuts.
 <p>
 @author Peter Karich
 */
@interface Path4CH : PathBidirRef {
}

- (instancetype)initWithGraph:(id<Graph>)routingGraph
                    withGraph:(id<Graph>)baseGraph
withComGraphhopperRoutingWeightingWeighting:(id<ComGraphhopperRoutingWeightingWeighting>)weighting;

- (void)processEdgeWithInt:(jint)tmpEdge
                   withInt:(jint)endNode
                   withInt:(jint)prevEdgeId;

@end

J2OBJC_EMPTY_STATIC_INIT(Path4CH)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef Path4CH ComGraphhopperRoutingChPath4CH;

J2OBJC_TYPE_LITERAL_HEADER(Path4CH)

#endif // _Path4CH_H_
