//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/iterator/TIntIterator.java
//

#ifndef _GnuTroveIteratorTIntIterator_H_
#define _GnuTroveIteratorTIntIterator_H_

#include "J2ObjC_header.h"
#include "gnu/trove/iterator/TIterator.h"

/**
 @brief Iterator for int collections.
 */
@protocol GnuTroveIteratorTIntIterator < GnuTroveIteratorTIterator, NSObject, JavaObject >
/**
 @brief Advances the iterator to the next element in the underlying collection and returns it.
 @return the next int in the collection
 @exception NoSuchElementException if the iterator is already exhausted
 */
- (jint)next;

@end

J2OBJC_EMPTY_STATIC_INIT(GnuTroveIteratorTIntIterator)

J2OBJC_TYPE_LITERAL_HEADER(GnuTroveIteratorTIntIterator)

#endif // _GnuTroveIteratorTIntIterator_H_
