//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/iterator/TLongIterator.java
//

#include "J2ObjC_source.h"
#include "gnu/trove/iterator/TLongIterator.h"

@interface GnuTroveIteratorTLongIterator : NSObject
@end

@implementation GnuTroveIteratorTLongIterator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "next", NULL, "J", 0x401, NULL },
  };
  static const J2ObjcClassInfo _GnuTroveIteratorTLongIterator = { 1, "TLongIterator", "gnu.trove.iterator", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_GnuTroveIteratorTLongIterator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GnuTroveIteratorTLongIterator)
