//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/iterator/TLongLongIterator.java
//

#include "J2ObjC_source.h"
#include "gnu/trove/iterator/TLongLongIterator.h"

@interface GnuTroveIteratorTLongLongIterator : NSObject
@end

@implementation GnuTroveIteratorTLongLongIterator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "key", NULL, "J", 0x401, NULL },
    { "value", NULL, "J", 0x401, NULL },
    { "setValueWithLong:", "setValue", "J", 0x401, NULL },
  };
  static const J2ObjcClassInfo _GnuTroveIteratorTLongLongIterator = { 1, "TLongLongIterator", "gnu.trove.iterator", NULL, 0x201, 3, methods, 0, NULL, 0, NULL};
  return &_GnuTroveIteratorTLongLongIterator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GnuTroveIteratorTLongLongIterator)
