//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/iterator/TPrimitiveIterator.java
//

#include "J2ObjC_source.h"
#include "gnu/trove/iterator/TPrimitiveIterator.h"

@interface GnuTroveIteratorTPrimitiveIterator : NSObject
@end

@implementation GnuTroveIteratorTPrimitiveIterator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "hasNext", NULL, "Z", 0x401, NULL },
    { "remove", NULL, "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _GnuTroveIteratorTPrimitiveIterator = { 1, "TPrimitiveIterator", "gnu.trove.iterator", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_GnuTroveIteratorTPrimitiveIterator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GnuTroveIteratorTPrimitiveIterator)
