//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/reader/DataReader.java
//

#ifndef _DataReader_H_
#define _DataReader_H_

@class EncodingManager;
@class JavaIoFile;
@class JavaUtilDate;
@protocol ComGraphhopperReaderDemElevationProvider;

#include "J2ObjC_header.h"

/**
 @author Peter Karich
 */
@protocol DataReader < NSObject, JavaObject >

- (id<DataReader>)setFileWithJavaIoFile:(JavaIoFile *)file;

- (id<DataReader>)setElevationProviderWithComGraphhopperReaderDemElevationProvider:(id<ComGraphhopperReaderDemElevationProvider>)ep;

- (id<DataReader>)setWorkerThreadsWithInt:(jint)workerThreads;

- (id<DataReader>)setEncodingManagerWithEncodingManager:(EncodingManager *)em;

- (id<DataReader>)setWayPointMaxDistanceWithDouble:(jdouble)wayPointMaxDistance;

/**
 @brief This method triggers reading the underlying data to create a graph
 */
- (void)readGraph;

/**
 @brief This method returns the date of the most recent change for the underlying data or null if not found.
 */
- (JavaUtilDate *)getDataDate;

@end

J2OBJC_EMPTY_STATIC_INIT(DataReader)

#define ComGraphhopperReaderDataReader DataReader

J2OBJC_TYPE_LITERAL_HEADER(DataReader)

#endif // _DataReader_H_
