//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/coll/GHTBitSet.java
//

#ifndef _GHTBitSet_H_
#define _GHTBitSet_H_

@class GnuTroveSetHashTIntHashSet;

#include "J2ObjC_header.h"
#include "com/graphhopper/coll/GHBitSet.h"

/**
 @brief Implements the bitset interface via a trove THashSet.
 More efficient for a few entries. <p>
 @author Peter Karich
 */
@interface GHTBitSet : NSObject < GHBitSet > {
}

- (instancetype)initWithGnuTroveSetHashTIntHashSet:(GnuTroveSetHashTIntHashSet *)set;

- (instancetype)initWithInt:(jint)no;

- (instancetype)init;

- (jboolean)containsWithInt:(jint)index;

- (void)addWithInt:(jint)index;

- (NSString *)description;

- (jint)getCardinality;

- (void)clear;

- (void)removeWithInt:(jint)index;

- (id<GHBitSet>)copyToWithGHBitSet:(id<GHBitSet>)bs OBJC_METHOD_FAMILY_NONE;

- (jint)nextWithInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(GHTBitSet)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef GHTBitSet ComGraphhopperCollGHTBitSet;

J2OBJC_TYPE_LITERAL_HEADER(GHTBitSet)

#endif // _GHTBitSet_H_
