//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/procedure/TDoubleProcedure.java
//

#ifndef _GnuTroveProcedureTDoubleProcedure_H_
#define _GnuTroveProcedureTDoubleProcedure_H_

#include "J2ObjC_header.h"

/**
 @brief Interface for procedures with one double parameter.
 */
@protocol GnuTroveProcedureTDoubleProcedure < NSObject, JavaObject >

/**
 @brief Executes this procedure.
 A false return value indicates that the application executing this procedure should not invoke this procedure again.
 @param value a value of type <code>double</code>
 @return true if additional invocations of the procedure are allowed.
 */
- (jboolean)executeWithDouble:(jdouble)value;

@end

J2OBJC_EMPTY_STATIC_INIT(GnuTroveProcedureTDoubleProcedure)

J2OBJC_TYPE_LITERAL_HEADER(GnuTroveProcedureTDoubleProcedure)

#endif // _GnuTroveProcedureTDoubleProcedure_H_
