//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/procedure/TIntIntProcedure.java
//

#ifndef _GnuTroveProcedureTIntIntProcedure_H_
#define _GnuTroveProcedureTIntIntProcedure_H_

#include "J2ObjC_header.h"

/**
 @brief Interface for procedures that take two parameters of type int and int.
 */
@protocol GnuTroveProcedureTIntIntProcedure < NSObject, JavaObject >

/**
 @brief Executes this procedure.
 A false return value indicates that the application executing this procedure should not invoke this procedure again.
 @param a a <code>int</code> value
 @param b a <code>int</code> value
 @return true if additional invocations of the procedure are allowed.
 */
- (jboolean)executeWithInt:(jint)a
                   withInt:(jint)b;

@end

J2OBJC_EMPTY_STATIC_INIT(GnuTroveProcedureTIntIntProcedure)

J2OBJC_TYPE_LITERAL_HEADER(GnuTroveProcedureTIntIntProcedure)

#endif // _GnuTroveProcedureTIntIntProcedure_H_
