//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/procedure/TIntObjectProcedure.java
//

#include "J2ObjC_source.h"
#include "gnu/trove/procedure/TIntObjectProcedure.h"

@interface GnuTroveProcedureTIntObjectProcedure : NSObject
@end

@implementation GnuTroveProcedureTIntObjectProcedure

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "executeWithInt:withId:", "execute", "Z", 0x401, NULL },
  };
  static const J2ObjcClassInfo _GnuTroveProcedureTIntObjectProcedure = { 1, "TIntObjectProcedure", "gnu.trove.procedure", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_GnuTroveProcedureTIntObjectProcedure;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GnuTroveProcedureTIntObjectProcedure)
