//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/shapes/Circle.java
//

#ifndef _Circle_H_
#define _Circle_H_

@class BBox;
@protocol DistanceCalc;

#include "J2ObjC_header.h"
#include "com/graphhopper/util/shapes/Shape.h"

/**
 @author Peter Karich
 */
@interface Circle : NSObject < Shape > {
}

- (instancetype)initWithDouble:(jdouble)lat
                    withDouble:(jdouble)lon
                    withDouble:(jdouble)radiusInMeter;

- (instancetype)initWithDouble:(jdouble)lat
                    withDouble:(jdouble)lon
                    withDouble:(jdouble)radiusInMeter
              withDistanceCalc:(id<DistanceCalc>)calc;

- (jdouble)getLat;

- (jdouble)getLon;

- (jboolean)containsWithDouble:(jdouble)lat1
                    withDouble:(jdouble)lon1;

- (BBox *)getBounds;

- (jboolean)intersectWithShape:(id<Shape>)o;

- (jboolean)containsWithShape:(id<Shape>)o;

- (jboolean)intersectWithBBox:(BBox *)b;

- (jboolean)intersectWithCircle:(Circle *)c;

- (jboolean)containsWithBBox:(BBox *)b;

- (jboolean)containsWithCircle:(Circle *)c;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(Circle)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef Circle ComGraphhopperUtilShapesCircle;

J2OBJC_TYPE_LITERAL_HEADER(Circle)

#endif // _Circle_H_
