//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/AbstractBidirAlgo.java
//

#ifndef _AbstractBidirAlgo_H_
#define _AbstractBidirAlgo_H_

@class Path;
@class TraversalModeEnum;
@protocol ComGraphhopperRoutingWeightingWeighting;
@protocol Graph;

#include "J2ObjC_header.h"
#include "com/graphhopper/routing/AbstractRoutingAlgorithm.h"

/**
 @brief Common subclass for bidirectional algorithms.
 <p>
 @author Peter Karich
 */
@interface AbstractBidirAlgo : AbstractRoutingAlgorithm {
 @public
  jboolean finishedFrom_;
  jboolean finishedTo_;
  jint visitedCountFrom_;
  jint visitedCountTo_;
}

- (instancetype)initWithGraph:(id<Graph>)graph
withComGraphhopperRoutingWeightingWeighting:(id<ComGraphhopperRoutingWeightingWeighting>)weighting
        withTraversalModeEnum:(TraversalModeEnum *)tMode;

- (void)initFromWithInt:(jint)from
             withDouble:(jdouble)dist OBJC_METHOD_FAMILY_NONE;

- (void)initToWithInt:(jint)to
           withDouble:(jdouble)dist OBJC_METHOD_FAMILY_NONE;

- (Path *)createAndInitPath;

- (jdouble)getCurrentFromWeight;

- (jdouble)getCurrentToWeight;

- (jboolean)fillEdgesFrom;

- (jboolean)fillEdgesTo;

- (Path *)calcPathWithInt:(jint)from
                  withInt:(jint)to;

- (void)runAlgo;

- (jint)getVisitedNodes;

@end

J2OBJC_EMPTY_STATIC_INIT(AbstractBidirAlgo)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef AbstractBidirAlgo ComGraphhopperRoutingAbstractBidirAlgo;

J2OBJC_TYPE_LITERAL_HEADER(AbstractBidirAlgo)

#endif // _AbstractBidirAlgo_H_
