//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/PathNative.java
//

#ifndef _PathNative_H_
#define _PathNative_H_

@class IOSIntArray;
@protocol ComGraphhopperRoutingWeightingWeighting;
@protocol Graph;

#include "J2ObjC_header.h"
#include "com/graphhopper/routing/Path.h"

/**
 @brief This class creates a Path from a DijkstraOneToMany node <p>
 @author Peter Karich
 */
@interface PathNative : Path {
}

- (instancetype)initWithGraph:(id<Graph>)g
withComGraphhopperRoutingWeightingWeighting:(id<ComGraphhopperRoutingWeightingWeighting>)weighting
                 withIntArray:(IOSIntArray *)parentNodes
                 withIntArray:(IOSIntArray *)parentEdges;

/**
 @brief Extracts path from two shortest-path-tree
 */
- (Path *)extract;

@end

J2OBJC_EMPTY_STATIC_INIT(PathNative)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef PathNative ComGraphhopperRoutingPathNative;

J2OBJC_TYPE_LITERAL_HEADER(PathNative)

#endif // _PathNative_H_
