//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/RoutingAlgorithm.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/routing/Path.h"
#include "com/graphhopper/routing/RoutingAlgorithm.h"
#include "java/util/List.h"

@interface RoutingAlgorithm : NSObject
@end

@implementation RoutingAlgorithm

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "calcPathWithInt:withInt:", "calcPath", "Lcom.graphhopper.routing.Path;", 0x401, NULL },
    { "calcPathsWithInt:withInt:", "calcPaths", "Ljava.util.List;", 0x401, NULL },
    { "setMaxVisitedNodesWithInt:", "setMaxVisitedNodes", "V", 0x401, NULL },
    { "getName", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "getVisitedNodes", NULL, "I", 0x401, NULL },
  };
  static const J2ObjcClassInfo _RoutingAlgorithm = { 1, "RoutingAlgorithm", "com.graphhopper.routing", NULL, 0x201, 5, methods, 0, NULL, 0, NULL};
  return &_RoutingAlgorithm;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(RoutingAlgorithm)
