//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/RoutingAlgorithmFactorySimple.java
//

#ifndef _RoutingAlgorithmFactorySimple_H_
#define _RoutingAlgorithmFactorySimple_H_

@class AlgorithmOptions;
@protocol ComGraphhopperRoutingWeightingWeightApproximator;
@protocol Graph;
@protocol NodeAccess;
@protocol RoutingAlgorithm;

#include "J2ObjC_header.h"
#include "com/graphhopper/routing/RoutingAlgorithmFactory.h"

/**
 @brief A simple factory creating normal algorithms (RoutingAlgorithm) without preparation.
 <p>
 @author Peter Karich
 */
@interface RoutingAlgorithmFactorySimple : NSObject < RoutingAlgorithmFactory > {
}

- (id<RoutingAlgorithm>)createAlgoWithGraph:(id<Graph>)g
                       withAlgorithmOptions:(AlgorithmOptions *)opts;

+ (id<ComGraphhopperRoutingWeightingWeightApproximator>)getApproximationWithNSString:(NSString *)prop
                                                                withAlgorithmOptions:(AlgorithmOptions *)opts
                                                                      withNodeAccess:(id<NodeAccess>)na;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(RoutingAlgorithmFactorySimple)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT id<ComGraphhopperRoutingWeightingWeightApproximator> RoutingAlgorithmFactorySimple_getApproximationWithNSString_withAlgorithmOptions_withNodeAccess_(NSString *prop, AlgorithmOptions *opts, id<NodeAccess> na);
CF_EXTERN_C_END

typedef RoutingAlgorithmFactorySimple ComGraphhopperRoutingRoutingAlgorithmFactorySimple;

J2OBJC_TYPE_LITERAL_HEADER(RoutingAlgorithmFactorySimple)

#endif // _RoutingAlgorithmFactorySimple_H_
