//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/reader/dem/BridgeElevationInterpolator.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/reader/dem/BridgeElevationInterpolator.h"
#include "com/graphhopper/routing/util/DataFlagEncoder.h"
#include "com/graphhopper/storage/GraphHopperStorage.h"
#include "com/graphhopper/util/EdgeIteratorState.h"

@implementation ComGraphhopperReaderDemBridgeElevationInterpolator

- (instancetype)initWithGraphHopperStorage:(GraphHopperStorage *)storage
                       withDataFlagEncoder:(DataFlagEncoder *)dataFlagEncoder {
  return [super initWithGraphHopperStorage:storage withDataFlagEncoder:dataFlagEncoder];
}

- (jboolean)isInterpolatableEdgeWithEdgeIteratorState:(id<EdgeIteratorState>)edge {
  return [((DataFlagEncoder *) nil_chk(dataFlagEncoder_)) isTransportModeBridgeWithEdgeIteratorState:edge];
}

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "initWithGraphHopperStorage:withDataFlagEncoder:", "BridgeElevationInterpolator", NULL, 0x1, NULL },
    { "isInterpolatableEdgeWithEdgeIteratorState:", "isInterpolatableEdge", "Z", 0x4, NULL },
  };
  static const J2ObjcClassInfo _ComGraphhopperReaderDemBridgeElevationInterpolator = { 1, "BridgeElevationInterpolator", "com.graphhopper.reader.dem", NULL, 0x1, 2, methods, 0, NULL, 0, NULL};
  return &_ComGraphhopperReaderDemBridgeElevationInterpolator;
}

@end

J2OBJC_CLASS_TYPE_LITERAL_SOURCE(ComGraphhopperReaderDemBridgeElevationInterpolator)
