//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/set/TIntSet.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "gnu/trove/TIntCollection.h"
#include "gnu/trove/iterator/TIntIterator.h"
#include "gnu/trove/procedure/TIntProcedure.h"
#include "gnu/trove/set/TIntSet.h"
#include "java/util/Collection.h"

@interface GnuTroveSetTIntSet : NSObject
@end

@implementation GnuTroveSetTIntSet

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getNoEntryValue", NULL, "I", 0x401, NULL },
    { "size", NULL, "I", 0x401, NULL },
    { "isEmpty", NULL, "Z", 0x401, NULL },
    { "containsWithInt:", "contains", "Z", 0x401, NULL },
    { "iterator", NULL, "Lgnu.trove.iterator.TIntIterator;", 0x401, NULL },
    { "toArray", NULL, "[I", 0x401, NULL },
    { "toArrayWithIntArray:", "toArray", "[I", 0x401, NULL },
    { "addWithInt:", "add", "Z", 0x401, NULL },
    { "removeWithInt:", "remove", "Z", 0x401, NULL },
    { "containsAllWithJavaUtilCollection:", "containsAll", "Z", 0x401, NULL },
    { "containsAllWithGnuTroveTIntCollection:", "containsAll", "Z", 0x401, NULL },
    { "containsAllWithIntArray:", "containsAll", "Z", 0x401, NULL },
    { "addAllWithJavaUtilCollection:", "addAll", "Z", 0x401, NULL },
    { "addAllWithGnuTroveTIntCollection:", "addAll", "Z", 0x401, NULL },
    { "addAllWithIntArray:", "addAll", "Z", 0x401, NULL },
    { "retainAllWithJavaUtilCollection:", "retainAll", "Z", 0x401, NULL },
    { "retainAllWithGnuTroveTIntCollection:", "retainAll", "Z", 0x401, NULL },
    { "retainAllWithIntArray:", "retainAll", "Z", 0x401, NULL },
    { "removeAllWithJavaUtilCollection:", "removeAll", "Z", 0x401, NULL },
    { "removeAllWithGnuTroveTIntCollection:", "removeAll", "Z", 0x401, NULL },
    { "removeAllWithIntArray:", "removeAll", "Z", 0x401, NULL },
    { "clear", NULL, "V", 0x401, NULL },
    { "forEachWithGnuTroveProcedureTIntProcedure:", "forEach", "Z", 0x401, NULL },
    { "isEqual:", "equals", "Z", 0x401, NULL },
    { "hash", "hashCode", "I", 0x401, NULL },
  };
  static const J2ObjcClassInfo _GnuTroveSetTIntSet = { 1, "TIntSet", "gnu.trove.set", NULL, 0x201, 25, methods, 0, NULL, 0, NULL};
  return &_GnuTroveSetTIntSet;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GnuTroveSetTIntSet)
