//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/util/AllCHEdgesIterator.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/routing/util/AllCHEdgesIterator.h"

@interface AllCHEdgesIterator : NSObject
@end

@implementation AllCHEdgesIterator

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcClassInfo _AllCHEdgesIterator = { 1, "AllCHEdgesIterator", "com.graphhopper.routing.util", NULL, 0x201, 0, NULL, 0, NULL, 0, NULL};
  return &_AllCHEdgesIterator;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(AllCHEdgesIterator)
