//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/util/RacingBikeFlagEncoder.java
//

#ifndef _RacingBikeFlagEncoder_H_
#define _RacingBikeFlagEncoder_H_

@class JavaUtilTreeMap;
@class PMap;
@class ReaderWay;

#include "J2ObjC_header.h"
#include "com/graphhopper/routing/util/BikeCommonFlagEncoder.h"

/**
 @brief Specifies the settings for race biking <p>
 @author ratrun
 @author Peter Karich
 */
@interface RacingBikeFlagEncoder : BikeCommonFlagEncoder {
}

- (instancetype)init;

- (instancetype)initWithPMap:(PMap *)properties;

- (instancetype)initWithNSString:(NSString *)propertiesStr;

- (instancetype)initWithInt:(jint)speedBits
                 withDouble:(jdouble)speedFactor
                    withInt:(jint)maxTurnCosts;

- (jint)getVersion;

- (void)collectWithReaderWay:(ReaderWay *)way
                  withDouble:(jdouble)wayTypeSpeed
         withJavaUtilTreeMap:(JavaUtilTreeMap *)weightToPrioMap;

- (jboolean)isPushingSectionWithReaderWay:(ReaderWay *)way;

- (jboolean)isSacScaleAllowedWithNSString:(NSString *)sacScale;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(RacingBikeFlagEncoder)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef RacingBikeFlagEncoder ComGraphhopperRoutingUtilRacingBikeFlagEncoder;

J2OBJC_TYPE_LITERAL_HEADER(RacingBikeFlagEncoder)

#endif // _RacingBikeFlagEncoder_H_
