//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/CHEdgeExplorer.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/util/CHEdgeExplorer.h"
#include "com/graphhopper/util/CHEdgeIterator.h"

@interface CHEdgeExplorer : NSObject
@end

@implementation CHEdgeExplorer

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "setBaseNodeWithInt:", "setBaseNode", "Lcom.graphhopper.util.CHEdgeIterator;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _CHEdgeExplorer = { 1, "CHEdgeExplorer", "com.graphhopper.util", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_CHEdgeExplorer;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(CHEdgeExplorer)
