//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/CHEdgeExplorer.java
//

#ifndef _CHEdgeExplorer_H_
#define _CHEdgeExplorer_H_

@protocol CHEdgeIterator;

#include "J2ObjC_header.h"
#include "com/graphhopper/util/EdgeExplorer.h"

/**
 @brief The edge explorer for CHGraph <p>
 @author Peter Karich
 */
@protocol CHEdgeExplorer < EdgeExplorer, NSObject, JavaObject >
- (id<CHEdgeIterator>)setBaseNodeWithInt:(jint)baseNode;

@end

J2OBJC_EMPTY_STATIC_INIT(CHEdgeExplorer)

#define ComGraphhopperUtilCHEdgeExplorer CHEdgeExplorer

J2OBJC_TYPE_LITERAL_HEADER(CHEdgeExplorer)

#endif // _CHEdgeExplorer_H_
