//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/CmdArgs.java
//

#ifndef _CmdArgs_H_
#define _CmdArgs_H_

@class IOSObjectArray;
@protocol JavaUtilMap;

#include "J2ObjC_header.h"
#include "com/graphhopper/util/PMap.h"

/**
 @brief Stores command line options in a map.
 The capitalization of the key is ignored. <p>
 @author Peter Karich
 */
@interface CmdArgs : PMap {
}

- (instancetype)init;

- (instancetype)initWithJavaUtilMap:(id<JavaUtilMap>)map;

/**
 @param fileStr the file name of config.properties
 @param systemProperty the property name of the configuration. E.g. -Dgraphhopper.config
 */
+ (CmdArgs *)readFromConfigWithNSString:(NSString *)fileStr
                           withNSString:(NSString *)systemProperty;

+ (CmdArgs *)readWithNSStringArray:(IOSObjectArray *)args;

/**
 @brief Command line configuration overwrites the ones in the config file.
 <p>
 @return a new CmdArgs object if necessary.
 */
+ (CmdArgs *)readFromConfigAndMergeWithCmdArgs:(CmdArgs *)args
                                  withNSString:(NSString *)configKey
                                  withNSString:(NSString *)configSysAttr;

- (CmdArgs *)putWithNSString:(NSString *)key
                      withId:(id)str;

@end

J2OBJC_EMPTY_STATIC_INIT(CmdArgs)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT CmdArgs *CmdArgs_readFromConfigWithNSString_withNSString_(NSString *fileStr, NSString *systemProperty);

FOUNDATION_EXPORT CmdArgs *CmdArgs_readWithNSStringArray_(IOSObjectArray *args);

FOUNDATION_EXPORT CmdArgs *CmdArgs_readFromConfigAndMergeWithCmdArgs_withNSString_withNSString_(CmdArgs *args, NSString *configKey, NSString *configSysAttr);
CF_EXTERN_C_END

typedef CmdArgs ComGraphhopperUtilCmdArgs;

J2OBJC_TYPE_LITERAL_HEADER(CmdArgs)

#endif // _CmdArgs_H_
