//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/DepthFirstSearch.java
//

#ifndef _DepthFirstSearch_H_
#define _DepthFirstSearch_H_

@protocol EdgeExplorer;

#include "J2ObjC_header.h"
#include "com/graphhopper/util/XFirstSearch.h"

/**
 @brief Implementation of depth first search (DFS) by LIFO queue <p>
 @author Peter Karich
 @author Jan Sölter
 */
@interface DepthFirstSearch : XFirstSearch {
}

/**
 @brief beginning with startNode add all following nodes to LIFO queue.
 If node has been already explored before, skip reexploration.
 */
- (void)startWithEdgeExplorer:(id<EdgeExplorer>)explorer
                      withInt:(jint)startNode;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(DepthFirstSearch)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef DepthFirstSearch ComGraphhopperUtilDepthFirstSearch;

J2OBJC_TYPE_LITERAL_HEADER(DepthFirstSearch)

#endif // _DepthFirstSearch_H_
