//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/DistanceCalc.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/util/DistanceCalc.h"
#include "com/graphhopper/util/shapes/BBox.h"
#include "com/graphhopper/util/shapes/GHPoint.h"

@interface DistanceCalc : NSObject
@end

@implementation DistanceCalc

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "createBBoxWithDouble:withDouble:withDouble:", "createBBox", "Lcom.graphhopper.util.shapes.BBox;", 0x401, NULL },
    { "calcCircumferenceWithDouble:", "calcCircumference", "D", 0x401, NULL },
    { "calcDistWithDouble:withDouble:withDouble:withDouble:", "calcDist", "D", 0x401, NULL },
    { "calcNormalizedDistWithDouble:", "calcNormalizedDist", "D", 0x401, NULL },
    { "calcDenormalizedDistWithDouble:", "calcDenormalizedDist", "D", 0x401, NULL },
    { "calcNormalizedDistWithDouble:withDouble:withDouble:withDouble:", "calcNormalizedDist", "D", 0x401, NULL },
    { "validEdgeDistanceWithDouble:withDouble:withDouble:withDouble:withDouble:withDouble:", "validEdgeDistance", "Z", 0x401, NULL },
    { "calcNormalizedEdgeDistanceWithDouble:withDouble:withDouble:withDouble:withDouble:withDouble:", "calcNormalizedEdgeDistance", "D", 0x401, NULL },
    { "calcCrossingPointToEdgeWithDouble:withDouble:withDouble:withDouble:withDouble:withDouble:", "calcCrossingPointToEdge", "Lcom.graphhopper.util.shapes.GHPoint;", 0x401, NULL },
    { "projectCoordinateWithDouble:withDouble:withDouble:withDouble:", "projectCoordinate", "Lcom.graphhopper.util.shapes.GHPoint;", 0x401, NULL },
    { "isCrossBoundaryWithDouble:withDouble:", "isCrossBoundary", "Z", 0x401, NULL },
  };
  static const J2ObjcClassInfo _DistanceCalc = { 1, "DistanceCalc", "com.graphhopper.util", NULL, 0x201, 11, methods, 0, NULL, 0, NULL};
  return &_DistanceCalc;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(DistanceCalc)
