//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/Downloader.java
//

#ifndef _Downloader_H_
#define _Downloader_H_

@class IOSObjectArray;
@class JavaIoInputStream;
@class JavaNetHttpURLConnection;

#include "J2ObjC_header.h"
#include "com/graphhopper/util/ProgressListener.h"

/**
 @author Peter Karich
 */
@interface Downloader : NSObject {
}

- (instancetype)initWithNSString:(NSString *)userAgent;

+ (void)mainWithNSStringArray:(IOSObjectArray *)args;

- (Downloader *)setTimeoutWithInt:(jint)timeout;

- (Downloader *)setReferrerWithNSString:(NSString *)referrer;

/**
 @brief This method initiates a connect call of the provided connection and returns the response stream.
 It only returns the error stream if it is available and readErrorStreamNoException is true otherwise it throws an IOException if an error happens. Furthermore it wraps the stream to decompress it if the connection content encoding is specified.
 */
- (JavaIoInputStream *)fetchWithJavaNetHttpURLConnection:(JavaNetHttpURLConnection *)connection
                                             withBoolean:(jboolean)readErrorStreamNoException;

- (JavaIoInputStream *)fetchWithNSString:(NSString *)url;

- (JavaNetHttpURLConnection *)createConnectionWithNSString:(NSString *)urlStr;

- (void)downloadFileWithNSString:(NSString *)url
                    withNSString:(NSString *)toFile;

- (void)downloadAndUnzipWithNSString:(NSString *)url
                        withNSString:(NSString *)toFolder
                withProgressListener:(id<ProgressListener>)progressListener;

- (NSString *)downloadAsStringWithNSString:(NSString *)url
                               withBoolean:(jboolean)readErrorStreamNoException;

@end

J2OBJC_EMPTY_STATIC_INIT(Downloader)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT void Downloader_mainWithNSStringArray_(IOSObjectArray *args);
CF_EXTERN_C_END

typedef Downloader ComGraphhopperUtilDownloader;

J2OBJC_TYPE_LITERAL_HEADER(Downloader)

@interface Downloader_$1 : NSObject < ProgressListener > {
}

- (void)updateWithLong:(jlong)val;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(Downloader_$1)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(Downloader_$1)

@interface Downloader_$2 : NSObject < ProgressListener > {
}

- (void)updateWithLong:(jlong)sumBytes;

- (instancetype)initWithProgressListener:(id<ProgressListener>)capture$0
                                 withInt:(jint)capture$1;

@end

J2OBJC_EMPTY_STATIC_INIT(Downloader_$2)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(Downloader_$2)

#endif // _Downloader_H_
