//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/EdgeExplorer.java
//

#ifndef _EdgeExplorer_H_
#define _EdgeExplorer_H_

@protocol EdgeIterator;

#include "J2ObjC_header.h"

/**
 @brief Class to get an EdgeIterator.
 Create it via graph.createEdgeExplorer() use one instance per thread. <p>
 @author Peter Karich
 */
@protocol EdgeExplorer < NSObject, JavaObject >

/**
 @brief This method sets the base node for iteration through neighboring edges (EdgeIteratorStates).
 <p>
 @return EdgeIterator around the specified baseNode. The resulting iterator can be a new instance or a reused instance returned in a previous call. So be sure you do not use the EdgeExplorer from multiple threads or in a nested loop.
 */
- (id<EdgeIterator>)setBaseNodeWithInt:(jint)baseNode;

@end

J2OBJC_EMPTY_STATIC_INIT(EdgeExplorer)

#define ComGraphhopperUtilEdgeExplorer EdgeExplorer

J2OBJC_TYPE_LITERAL_HEADER(EdgeExplorer)

#endif // _EdgeExplorer_H_
