//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/NotThreadSafe.java
//

#ifndef _NotThreadSafe_H_
#define _NotThreadSafe_H_

#include "J2ObjC_header.h"
#include "java/lang/annotation/Annotation.h"

@protocol NotThreadSafe < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(NotThreadSafe)

J2OBJC_TYPE_LITERAL_HEADER(NotThreadSafe)

#endif // _NotThreadSafe_H_
