//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/NumHelper.java
//

#ifndef _NumHelper_H_
#define _NumHelper_H_

#include "J2ObjC_header.h"

#define NumHelper_DEFAULT_PRECISION 1.0E-6

/**
 @author Peter Karich
 */
@interface NumHelper : NSObject {
}

+ (jboolean)equalsEpsWithDouble:(jdouble)d1
                     withDouble:(jdouble)d2;

+ (jboolean)equalsEpsWithDouble:(jdouble)d1
                     withDouble:(jdouble)d2
                     withDouble:(jdouble)epsilon;

+ (jboolean)equalsWithDouble:(jdouble)d1
                  withDouble:(jdouble)d2;

+ (jint)compareWithDouble:(jdouble)d1
               withDouble:(jdouble)d2;

+ (jboolean)equalsEpsWithFloat:(jfloat)d1
                     withFloat:(jfloat)d2;

+ (jboolean)equalsEpsWithFloat:(jfloat)d1
                     withFloat:(jfloat)d2
                     withFloat:(jfloat)epsilon;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(NumHelper)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT jboolean NumHelper_equalsEpsWithDouble_withDouble_(jdouble d1, jdouble d2);

FOUNDATION_EXPORT jboolean NumHelper_equalsEpsWithDouble_withDouble_withDouble_(jdouble d1, jdouble d2, jdouble epsilon);

FOUNDATION_EXPORT jboolean NumHelper_equalsWithDouble_withDouble_(jdouble d1, jdouble d2);

FOUNDATION_EXPORT jint NumHelper_compareWithDouble_withDouble_(jdouble d1, jdouble d2);

FOUNDATION_EXPORT jboolean NumHelper_equalsEpsWithFloat_withFloat_(jfloat d1, jfloat d2);

FOUNDATION_EXPORT jboolean NumHelper_equalsEpsWithFloat_withFloat_withFloat_(jfloat d1, jfloat d2, jfloat epsilon);

J2OBJC_STATIC_FIELD_GETTER(NumHelper, DEFAULT_PRECISION, jdouble)
CF_EXTERN_C_END

typedef NumHelper ComGraphhopperUtilNumHelper;

J2OBJC_TYPE_LITERAL_HEADER(NumHelper)

#endif // _NumHelper_H_
