//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/PathMerger.java
//

#ifndef _PathMerger_H_
#define _PathMerger_H_

@class DouglasPeucker;
@class PathWrapper;
@class PointList;
@protocol JavaUtilList;
@protocol Translation;

#include "J2ObjC_header.h"

/**
 @brief This class merges a list of points into one point recognizing the specified places.
 <p>
 @author Peter Karich
 @author ratrun
 */
@interface PathMerger : NSObject {
}

- (PathMerger *)setCalcPointsWithBoolean:(jboolean)calcPoints;

- (PathMerger *)setDouglasPeuckerWithDouglasPeucker:(DouglasPeucker *)douglasPeucker;

- (PathMerger *)setSimplifyResponseWithBoolean:(jboolean)simplifyRes;

- (PathMerger *)setEnableInstructionsWithBoolean:(jboolean)enableInstructions;

- (void)doWorkWithPathWrapper:(PathWrapper *)altRsp
             withJavaUtilList:(id<JavaUtilList>)paths
              withTranslation:(id<Translation>)tr;

- (instancetype)init;

@end

FOUNDATION_EXPORT BOOL PathMerger_initialized;
J2OBJC_STATIC_INIT(PathMerger)

CF_EXTERN_C_BEGIN

FOUNDATION_EXPORT DouglasPeucker *PathMerger_DP_;
J2OBJC_STATIC_FIELD_GETTER(PathMerger, DP_, DouglasPeucker *)
CF_EXTERN_C_END

typedef PathMerger ComGraphhopperUtilPathMerger;

J2OBJC_TYPE_LITERAL_HEADER(PathMerger)

#endif // _PathMerger_H_
