//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/storage/GraphStorage.java
//

#ifndef _GraphStorage_H_
#define _GraphStorage_H_

@class EncodingManager;
@class StorableProperties;
@protocol Directory;

#include "J2ObjC_header.h"
#include "com/graphhopper/storage/Storable.h"

@protocol GraphStorage < Storable, NSObject, JavaObject >
- (id<Directory>)getDirectory;

- (EncodingManager *)getEncodingManager;

- (void)setSegmentSizeWithInt:(jint)bytes;

- (NSString *)toDetailsString;

- (StorableProperties *)getProperties;

/**
 @brief Schedule the deletion of the specified node until an optimize() call happens
 */
- (void)markNodeRemovedWithInt:(jint)index;

/**
 @brief Checks if the specified node is marked as removed.
 */
- (jboolean)isNodeRemovedWithInt:(jint)index;

/**
 @brief Performs optimization routines like deletion or node rearrangements.
 */
- (void)optimize;

@end

J2OBJC_EMPTY_STATIC_INIT(GraphStorage)

#define ComGraphhopperStorageGraphStorage GraphStorage

J2OBJC_TYPE_LITERAL_HEADER(GraphStorage)

#endif // _GraphStorage_H_
