//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/storage/NodeAccess.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/storage/NodeAccess.h"

@interface NodeAccess : NSObject
@end

@implementation NodeAccess

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getAdditionalNodeFieldWithInt:", "getAdditionalNodeField", "I", 0x401, NULL },
    { "setAdditionalNodeFieldWithInt:withInt:", "setAdditionalNodeField", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _NodeAccess = { 1, "NodeAccess", "com.graphhopper.storage", NULL, 0x201, 2, methods, 0, NULL, 0, NULL};
  return &_NodeAccess;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(NodeAccess)
