//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/storage/SPTEntry.java
//

#ifndef _SPTEntry_H_
#define _SPTEntry_H_

#include "J2ObjC_header.h"
#include "java/lang/Comparable.h"

/**
 @brief This class is used to create the shortest-path-tree from linked entities.
 <p>
 @author Peter Karich
 */
@interface SPTEntry : NSObject < NSCopying, JavaLangComparable > {
 @public
  jint edge_;
  jint adjNode_;
  jdouble weight_;
  SPTEntry *parent_;
}

- (instancetype)initWithInt:(jint)edgeId
                    withInt:(jint)adjNode
                 withDouble:(jdouble)weight;

/**
 @brief This method returns the weight to the origin e.g. to the start for the forward SPT and to the destination for the backward SPT.
 Where the variable 'weight' is used to let heap select smallest *full* weight (from start to destination).
 */
- (jdouble)getWeightOfVisitedPath;

- (SPTEntry *)clone;

- (SPTEntry *)cloneFull;

- (jint)compareToWithId:(SPTEntry *)o;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(SPTEntry)

J2OBJC_FIELD_SETTER(SPTEntry, parent_, SPTEntry *)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

typedef SPTEntry ComGraphhopperStorageSPTEntry;

J2OBJC_TYPE_LITERAL_HEADER(SPTEntry)

#endif // _SPTEntry_H_
