//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/storage/TurnCostExtension.java
//

#ifndef _TurnCostExtension_H_
#define _TurnCostExtension_H_

@protocol DataAccess;
@protocol Directory;
@protocol Graph;
@protocol NodeAccess;

#include "J2ObjC_header.h"
#include "com/graphhopper/storage/GraphExtension.h"

#define TurnCostExtension_EMPTY_FLAGS 0LL
#define TurnCostExtension_NO_TURN_ENTRY -1

/**
 @brief Holds turn cost tables for each node.
 The additional field of a node will be used to point towards the first entry within a node cost table to identify turn restrictions, or later, turn getCosts. <p>
 @author Karl Hübner
 @author Peter Karich
 */
@interface TurnCostExtension : NSObject < GraphExtension > {
}

- (instancetype)init;

- (void)init__WithGraph:(id<Graph>)graph
          withDirectory:(id<Directory>)dir OBJC_METHOD_FAMILY_NONE;

- (void)setSegmentSizeWithInt:(jint)bytes;

- (TurnCostExtension *)createWithLong:(jlong)initBytes;

- (void)flush;

- (void)close;

- (jlong)getCapacity;

- (jboolean)loadExisting;

/**
 @brief This method adds a new entry which is a turn restriction or cost information via the turnFlags.
 */
- (void)addTurnInfoWithInt:(jint)fromEdge
                   withInt:(jint)viaNode
                   withInt:(jint)toEdge
                  withLong:(jlong)turnFlags;

/**
 @return turn flags of the specified node and edge properties.
 */
- (jlong)getTurnCostFlagsWithInt:(jint)edgeFrom
                         withInt:(jint)nodeVia
                         withInt:(jint)edgeTo;

- (jboolean)isRequireNodeField;

- (jboolean)isRequireEdgeField;

- (jint)getDefaultNodeFieldValue;

- (jint)getDefaultEdgeFieldValue;

- (id<GraphExtension>)copyToWithGraphExtension:(id<GraphExtension>)clonedStorage OBJC_METHOD_FAMILY_NONE;

- (jboolean)isClosed;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(TurnCostExtension)

CF_EXTERN_C_BEGIN

J2OBJC_STATIC_FIELD_GETTER(TurnCostExtension, NO_TURN_ENTRY, jint)

J2OBJC_STATIC_FIELD_GETTER(TurnCostExtension, EMPTY_FLAGS, jlong)
CF_EXTERN_C_END

typedef TurnCostExtension ComGraphhopperStorageTurnCostExtension;

J2OBJC_TYPE_LITERAL_HEADER(TurnCostExtension)

#endif // _TurnCostExtension_H_
