//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/weighting/AbstractAdjustedWeighting.java
//

#ifndef _ComGraphhopperRoutingWeightingAbstractAdjustedWeighting_H_
#define _ComGraphhopperRoutingWeightingAbstractAdjustedWeighting_H_

@class HintsMap;
@protocol EdgeIteratorState;
@protocol FlagEncoder;

#include "J2ObjC_header.h"
#include "com/graphhopper/routing/weighting/Weighting.h"

/**
 @brief The AdjustedWeighting wraps another Weighting.
 @author Robin Boldt
 */
@interface ComGraphhopperRoutingWeightingAbstractAdjustedWeighting : NSObject < ComGraphhopperRoutingWeightingWeighting > {
 @public
  id<ComGraphhopperRoutingWeightingWeighting> superWeighting_;
}

- (instancetype)initWithComGraphhopperRoutingWeightingWeighting:(id<ComGraphhopperRoutingWeightingWeighting>)superWeighting;

- (jlong)calcMillisWithEdgeIteratorState:(id<EdgeIteratorState>)edgeState
                             withBoolean:(jboolean)reverse
                                 withInt:(jint)prevOrNextEdgeId;

/**
 @brief Returns the flagEncoder of the superWeighting.
 Usually we do not have a Flagencoder here.
 */
- (id<FlagEncoder>)getFlagEncoder;

- (jboolean)matchesWithHintsMap:(HintsMap *)reqMap;

- (NSString *)description;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGraphhopperRoutingWeightingAbstractAdjustedWeighting)

J2OBJC_FIELD_SETTER(ComGraphhopperRoutingWeightingAbstractAdjustedWeighting, superWeighting_, id<ComGraphhopperRoutingWeightingWeighting>)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(ComGraphhopperRoutingWeightingAbstractAdjustedWeighting)

#endif // _ComGraphhopperRoutingWeightingAbstractAdjustedWeighting_H_
