//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/routing/weighting/Weighting.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/routing/util/FlagEncoder.h"
#include "com/graphhopper/routing/util/HintsMap.h"
#include "com/graphhopper/routing/weighting/Weighting.h"
#include "com/graphhopper/util/EdgeIteratorState.h"

@interface ComGraphhopperRoutingWeightingWeighting : NSObject
@end

@implementation ComGraphhopperRoutingWeightingWeighting

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getMinWeightWithDouble:", "getMinWeight", "D", 0x401, NULL },
    { "calcWeightWithEdgeIteratorState:withBoolean:withInt:", "calcWeight", "D", 0x401, NULL },
    { "calcMillisWithEdgeIteratorState:withBoolean:withInt:", "calcMillis", "J", 0x401, NULL },
    { "getFlagEncoder", NULL, "Lcom.graphhopper.routing.util.FlagEncoder;", 0x401, NULL },
    { "getName", NULL, "Ljava.lang.String;", 0x401, NULL },
    { "matchesWithHintsMap:", "matches", "Z", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComGraphhopperRoutingWeightingWeighting = { 1, "Weighting", "com.graphhopper.routing.weighting", NULL, 0x201, 6, methods, 0, NULL, 0, NULL};
  return &_ComGraphhopperRoutingWeightingWeighting;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGraphhopperRoutingWeightingWeighting)
