//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/junit/build_result/java/org/junit/runners/model/Statement.java
//

#ifndef _OrgJunitRunnersModelStatement_H_
#define _OrgJunitRunnersModelStatement_H_

#include "J2ObjC_header.h"

@interface OrgJunitRunnersModelStatement : NSObject {
}

- (void)evaluate;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersModelStatement)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersModelStatement)

#endif // _OrgJunitRunnersModelStatement_H_
