//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/exceptions/GHException.java
//

#include "J2ObjC_source.h"
#include "com/graphhopper/util/exceptions/GHException.h"
#include "java/util/Map.h"

@interface ComGraphhopperUtilExceptionsGHException : NSObject
@end

@implementation ComGraphhopperUtilExceptionsGHException

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getDetails", NULL, "Ljava.util.Map;", 0x401, NULL },
  };
  static const J2ObjcClassInfo _ComGraphhopperUtilExceptionsGHException = { 1, "GHException", "com.graphhopper.util.exceptions", NULL, 0x201, 1, methods, 0, NULL, 0, NULL};
  return &_ComGraphhopperUtilExceptionsGHException;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(ComGraphhopperUtilExceptionsGHException)
