//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: graphhopper/core/src/main/java/com/graphhopper/util/exceptions/GHException.java
//

#ifndef _ComGraphhopperUtilExceptionsGHException_H_
#define _ComGraphhopperUtilExceptionsGHException_H_

@protocol JavaUtilMap;

#include "J2ObjC_header.h"

/**
 @brief Generic GHException that allows to add details to the exception message
 @author Robin Boldt
 */
@protocol ComGraphhopperUtilExceptionsGHException < NSObject, JavaObject >

- (id<JavaUtilMap>)getDetails;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGraphhopperUtilExceptionsGHException)

J2OBJC_TYPE_LITERAL_HEADER(ComGraphhopperUtilExceptionsGHException)

#endif // _ComGraphhopperUtilExceptionsGHException_H_
