//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc/testing/mockito/build_result/java/org/mockito/internal/handler/MockHandlerFactory.java
//

#ifndef _OrgMockitoInternalHandlerMockHandlerFactory_H_
#define _OrgMockitoInternalHandlerMockHandlerFactory_H_

@protocol OrgMockitoInternalInternalMockHandler;
@protocol OrgMockitoMockMockCreationSettings;

#include "J2ObjC_header.h"

@interface OrgMockitoInternalHandlerMockHandlerFactory : NSObject {
}

- (id<OrgMockitoInternalInternalMockHandler>)createWithOrgMockitoMockMockCreationSettings:(id<OrgMockitoMockMockCreationSettings>)settings;

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalHandlerMockHandlerFactory)

CF_EXTERN_C_BEGIN
CF_EXTERN_C_END

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalHandlerMockHandlerFactory)

#endif // _OrgMockitoInternalHandlerMockHandlerFactory_H_
