//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: dependencies/trove/src/gnu/trove/stack/TIntStack.java
//

#include "IOSPrimitiveArray.h"
#include "J2ObjC_source.h"
#include "gnu/trove/stack/TIntStack.h"

@interface GnuTroveStackTIntStack : NSObject
@end

@implementation GnuTroveStackTIntStack

+ (const J2ObjcClassInfo *)__metadata {
  static const J2ObjcMethodInfo methods[] = {
    { "getNoEntryValue", NULL, "I", 0x401, NULL },
    { "pushWithInt:", "push", "V", 0x401, NULL },
    { "pop", NULL, "I", 0x401, NULL },
    { "peek", NULL, "I", 0x401, NULL },
    { "size", NULL, "I", 0x401, NULL },
    { "clear", NULL, "V", 0x401, NULL },
    { "toArray", NULL, "[I", 0x401, NULL },
    { "toArrayWithIntArray:", "toArray", "V", 0x401, NULL },
  };
  static const J2ObjcClassInfo _GnuTroveStackTIntStack = { 1, "TIntStack", "gnu.trove.stack", NULL, 0x201, 8, methods, 0, NULL, 0, NULL};
  return &_GnuTroveStackTIntStack;
}

@end

J2OBJC_INTERFACE_TYPE_LITERAL_SOURCE(GnuTroveStackTIntStack)
